### ISSUE TITLE
seems to ignore persistent routes on windows

### ISSUE THREAD

**Issue by mpictor** [moriyoshi/routewrapper#1]
I need data about persistent routes, but unfortunately that data seems to be ignored by this package. I considered adding support, but found your (hand-written?) parser confusing. Not to mention, I only have a single platform (Windows Embedded 8) to test on.

For now, I'm using `powershell get-netroute -policystore persistentstore` instead.

----

Thank you for writing this package, it looks like it would be quite useful anywhere cross-platform routing is needed. I don't like that it shells out and parses the command's stdout, but then again that's precisely what I'm doing on windows to get routes, vlans, etc.

**Comment by moriyoshi** [comment]
This was fixed at 334b2ff . Thanks for the bug report!
